//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	topologyv1beta1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
	"github.com/openstack-k8s-operators/lib-common/modules/common/condition"
	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialSelectors) DeepCopyInto(out *CredentialSelectors) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialSelectors.
func (in *CredentialSelectors) DeepCopy() *CredentialSelectors {
	if in == nil {
		return nil
	}
	out := new(CredentialSelectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedEmbeddedLabelsAnnotations) DeepCopyInto(out *DeprecatedEmbeddedLabelsAnnotations) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedEmbeddedLabelsAnnotations.
func (in *DeprecatedEmbeddedLabelsAnnotations) DeepCopy() *DeprecatedEmbeddedLabelsAnnotations {
	if in == nil {
		return nil
	}
	out := new(DeprecatedEmbeddedLabelsAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedEmbeddedObjectMeta) DeepCopyInto(out *DeprecatedEmbeddedObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedEmbeddedObjectMeta.
func (in *DeprecatedEmbeddedObjectMeta) DeepCopy() *DeprecatedEmbeddedObjectMeta {
	if in == nil {
		return nil
	}
	out := new(DeprecatedEmbeddedObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedPersistenceSpec) DeepCopyInto(out *DeprecatedPersistenceSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedPersistenceSpec.
func (in *DeprecatedPersistenceSpec) DeepCopy() *DeprecatedPersistenceSpec {
	if in == nil {
		return nil
	}
	out := new(DeprecatedPersistenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedPodTemplateSpec) DeepCopyInto(out *DeprecatedPodTemplateSpec) {
	*out = *in
	if in.DeprecatedEmbeddedObjectMeta != nil {
		in, out := &in.DeprecatedEmbeddedObjectMeta, &out.DeprecatedEmbeddedObjectMeta
		*out = new(DeprecatedEmbeddedObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(corev1.PodSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedPodTemplateSpec.
func (in *DeprecatedPodTemplateSpec) DeepCopy() *DeprecatedPodTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(DeprecatedPodTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedRabbitMQServiceSpec) DeepCopyInto(out *DeprecatedRabbitMQServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IPFamilyPolicy != nil {
		in, out := &in.IPFamilyPolicy, &out.IPFamilyPolicy
		*out = new(corev1.IPFamilyPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedRabbitMQServiceSpec.
func (in *DeprecatedRabbitMQServiceSpec) DeepCopy() *DeprecatedRabbitMQServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DeprecatedRabbitMQServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedRabbitmqConfigSpec) DeepCopyInto(out *DeprecatedRabbitmqConfigSpec) {
	*out = *in
	if in.AdditionalPlugins != nil {
		in, out := &in.AdditionalPlugins, &out.AdditionalPlugins
		*out = make([]RabbitMQPlugin, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedRabbitmqConfigSpec.
func (in *DeprecatedRabbitmqConfigSpec) DeepCopy() *DeprecatedRabbitmqConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DeprecatedRabbitmqConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedSecretBackendSpec) DeepCopyInto(out *DeprecatedSecretBackendSpec) {
	*out = *in
	if in.ExternalSecret != nil {
		in, out := &in.ExternalSecret, &out.ExternalSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(DeprecatedVaultSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedSecretBackendSpec.
func (in *DeprecatedSecretBackendSpec) DeepCopy() *DeprecatedSecretBackendSpec {
	if in == nil {
		return nil
	}
	out := new(DeprecatedSecretBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedStatefulSetOverride) DeepCopyInto(out *DeprecatedStatefulSetOverride) {
	*out = *in
	if in.DeprecatedEmbeddedLabelsAnnotations != nil {
		in, out := &in.DeprecatedEmbeddedLabelsAnnotations, &out.DeprecatedEmbeddedLabelsAnnotations
		*out = new(DeprecatedEmbeddedLabelsAnnotations)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(DeprecatedStatefulSetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedStatefulSetOverride.
func (in *DeprecatedStatefulSetOverride) DeepCopy() *DeprecatedStatefulSetOverride {
	if in == nil {
		return nil
	}
	out := new(DeprecatedStatefulSetOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedStatefulSetSpec) DeepCopyInto(out *DeprecatedStatefulSetSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(DeprecatedPodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeClaimTemplates != nil {
		in, out := &in.VolumeClaimTemplates, &out.VolumeClaimTemplates
		*out = make([]corev1.PersistentVolumeClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(appsv1.StatefulSetUpdateStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.PersistentVolumeClaimRetentionPolicy != nil {
		in, out := &in.PersistentVolumeClaimRetentionPolicy, &out.PersistentVolumeClaimRetentionPolicy
		*out = new(appsv1.StatefulSetPersistentVolumeClaimRetentionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedStatefulSetSpec.
func (in *DeprecatedStatefulSetSpec) DeepCopy() *DeprecatedStatefulSetSpec {
	if in == nil {
		return nil
	}
	out := new(DeprecatedStatefulSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedVaultSpec) DeepCopyInto(out *DeprecatedVaultSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(DeprecatedVaultTLSSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedVaultSpec.
func (in *DeprecatedVaultSpec) DeepCopy() *DeprecatedVaultSpec {
	if in == nil {
		return nil
	}
	out := new(DeprecatedVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedVaultTLSSpec) DeepCopyInto(out *DeprecatedVaultTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedVaultTLSSpec.
func (in *DeprecatedVaultTLSSpec) DeepCopy() *DeprecatedVaultTLSSpec {
	if in == nil {
		return nil
	}
	out := new(DeprecatedVaultTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodOverride) DeepCopyInto(out *PodOverride) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]service.OverrideSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodOverride.
func (in *PodOverride) DeepCopy() *PodOverride {
	if in == nil {
		return nil
	}
	out := new(PodOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQOverrideSpec) DeepCopyInto(out *RabbitMQOverrideSpec) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(RabbitMQServiceOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.StatefulSet != nil {
		in, out := &in.StatefulSet, &out.StatefulSet
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQOverrideSpec.
func (in *RabbitMQOverrideSpec) DeepCopy() *RabbitMQOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(RabbitMQOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQPolicy) DeepCopyInto(out *RabbitMQPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQPolicy.
func (in *RabbitMQPolicy) DeepCopy() *RabbitMQPolicy {
	if in == nil {
		return nil
	}
	out := new(RabbitMQPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RabbitMQPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQPolicyList) DeepCopyInto(out *RabbitMQPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RabbitMQPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQPolicyList.
func (in *RabbitMQPolicyList) DeepCopy() *RabbitMQPolicyList {
	if in == nil {
		return nil
	}
	out := new(RabbitMQPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RabbitMQPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQPolicySpec) DeepCopyInto(out *RabbitMQPolicySpec) {
	*out = *in
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQPolicySpec.
func (in *RabbitMQPolicySpec) DeepCopy() *RabbitMQPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RabbitMQPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQPolicyStatus) DeepCopyInto(out *RabbitMQPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQPolicyStatus.
func (in *RabbitMQPolicyStatus) DeepCopy() *RabbitMQPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RabbitMQPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQServiceOverride) DeepCopyInto(out *RabbitMQServiceOverride) {
	*out = *in
	if in.EmbeddedLabelsAnnotations != nil {
		in, out := &in.EmbeddedLabelsAnnotations, &out.EmbeddedLabelsAnnotations
		*out = new(service.EmbeddedLabelsAnnotations)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(corev1.ServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQServiceOverride.
func (in *RabbitMQServiceOverride) DeepCopy() *RabbitMQServiceOverride {
	if in == nil {
		return nil
	}
	out := new(RabbitMQServiceOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQTLSSpec) DeepCopyInto(out *RabbitMQTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQTLSSpec.
func (in *RabbitMQTLSSpec) DeepCopy() *RabbitMQTLSSpec {
	if in == nil {
		return nil
	}
	out := new(RabbitMQTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQUser) DeepCopyInto(out *RabbitMQUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQUser.
func (in *RabbitMQUser) DeepCopy() *RabbitMQUser {
	if in == nil {
		return nil
	}
	out := new(RabbitMQUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RabbitMQUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQUserList) DeepCopyInto(out *RabbitMQUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RabbitMQUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQUserList.
func (in *RabbitMQUserList) DeepCopy() *RabbitMQUserList {
	if in == nil {
		return nil
	}
	out := new(RabbitMQUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RabbitMQUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQUserPermissions) DeepCopyInto(out *RabbitMQUserPermissions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQUserPermissions.
func (in *RabbitMQUserPermissions) DeepCopy() *RabbitMQUserPermissions {
	if in == nil {
		return nil
	}
	out := new(RabbitMQUserPermissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQUserSpec) DeepCopyInto(out *RabbitMQUserSpec) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
	if in.CredentialSelectors != nil {
		in, out := &in.CredentialSelectors, &out.CredentialSelectors
		*out = new(CredentialSelectors)
		**out = **in
	}
	out.Permissions = in.Permissions
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQUserSpec.
func (in *RabbitMQUserSpec) DeepCopy() *RabbitMQUserSpec {
	if in == nil {
		return nil
	}
	out := new(RabbitMQUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQUserStatus) DeepCopyInto(out *RabbitMQUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQUserStatus.
func (in *RabbitMQUserStatus) DeepCopy() *RabbitMQUserStatus {
	if in == nil {
		return nil
	}
	out := new(RabbitMQUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQVhost) DeepCopyInto(out *RabbitMQVhost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQVhost.
func (in *RabbitMQVhost) DeepCopy() *RabbitMQVhost {
	if in == nil {
		return nil
	}
	out := new(RabbitMQVhost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RabbitMQVhost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQVhostList) DeepCopyInto(out *RabbitMQVhostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RabbitMQVhost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQVhostList.
func (in *RabbitMQVhostList) DeepCopy() *RabbitMQVhostList {
	if in == nil {
		return nil
	}
	out := new(RabbitMQVhostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RabbitMQVhostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQVhostSpec) DeepCopyInto(out *RabbitMQVhostSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQVhostSpec.
func (in *RabbitMQVhostSpec) DeepCopy() *RabbitMQVhostSpec {
	if in == nil {
		return nil
	}
	out := new(RabbitMQVhostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQVhostStatus) DeepCopyInto(out *RabbitMQVhostStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQVhostStatus.
func (in *RabbitMQVhostStatus) DeepCopy() *RabbitMQVhostStatus {
	if in == nil {
		return nil
	}
	out := new(RabbitMQVhostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMq) DeepCopyInto(out *RabbitMq) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMq.
func (in *RabbitMq) DeepCopy() *RabbitMq {
	if in == nil {
		return nil
	}
	out := new(RabbitMq)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RabbitMq) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMqConfig) DeepCopyInto(out *RabbitMqConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMqConfig.
func (in *RabbitMqConfig) DeepCopy() *RabbitMqConfig {
	if in == nil {
		return nil
	}
	out := new(RabbitMqConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMqDefaults) DeepCopyInto(out *RabbitMqDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMqDefaults.
func (in *RabbitMqDefaults) DeepCopy() *RabbitMqDefaults {
	if in == nil {
		return nil
	}
	out := new(RabbitMqDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMqList) DeepCopyInto(out *RabbitMqList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RabbitMq, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMqList.
func (in *RabbitMqList) DeepCopy() *RabbitMqList {
	if in == nil {
		return nil
	}
	out := new(RabbitMqList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RabbitMqList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMqSpec) DeepCopyInto(out *RabbitMqSpec) {
	*out = *in
	in.RabbitMqSpecCore.DeepCopyInto(&out.RabbitMqSpecCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMqSpec.
func (in *RabbitMqSpec) DeepCopy() *RabbitMqSpec {
	if in == nil {
		return nil
	}
	out := new(RabbitMqSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMqSpecCore) DeepCopyInto(out *RabbitMqSpecCore) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	out.TLS = in.TLS
	in.Override.DeepCopyInto(&out.Override)
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.TopologyRef != nil {
		in, out := &in.TopologyRef, &out.TopologyRef
		*out = new(topologyv1beta1.TopoRef)
		**out = **in
	}
	if in.QueueType != nil {
		in, out := &in.QueueType, &out.QueueType
		*out = new(QueueType)
		**out = **in
	}
	if in.PodOverride != nil {
		in, out := &in.PodOverride, &out.PodOverride
		*out = new(PodOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.DelayStartSeconds != nil {
		in, out := &in.DelayStartSeconds, &out.DelayStartSeconds
		*out = new(int32)
		**out = **in
	}
	if in.TargetVersion != nil {
		in, out := &in.TargetVersion, &out.TargetVersion
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(DeprecatedRabbitMQServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Persistence.DeepCopyInto(&out.Persistence)
	in.Rabbitmq.DeepCopyInto(&out.Rabbitmq)
	if in.SecretBackend != nil {
		in, out := &in.SecretBackend, &out.SecretBackend
		*out = new(DeprecatedSecretBackendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Test != nil {
		in, out := &in.Test, &out.Test
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMqSpecCore.
func (in *RabbitMqSpecCore) DeepCopy() *RabbitMqSpecCore {
	if in == nil {
		return nil
	}
	out := new(RabbitMqSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMqStatus) DeepCopyInto(out *RabbitMqStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAppliedTopology != nil {
		in, out := &in.LastAppliedTopology, &out.LastAppliedTopology
		*out = new(topologyv1beta1.TopoRef)
		**out = **in
	}
	if in.DefaultUser != nil {
		in, out := &in.DefaultUser, &out.DefaultUser
		*out = new(RabbitmqClusterDefaultUser)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceHostnames != nil {
		in, out := &in.ServiceHostnames, &out.ServiceHostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMqStatus.
func (in *RabbitMqStatus) DeepCopy() *RabbitMqStatus {
	if in == nil {
		return nil
	}
	out := new(RabbitMqStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqClusterDefaultUser) DeepCopyInto(out *RabbitmqClusterDefaultUser) {
	*out = *in
	if in.SecretReference != nil {
		in, out := &in.SecretReference, &out.SecretReference
		*out = new(RabbitmqClusterSecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceReference != nil {
		in, out := &in.ServiceReference, &out.ServiceReference
		*out = new(RabbitmqClusterServiceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitmqClusterDefaultUser.
func (in *RabbitmqClusterDefaultUser) DeepCopy() *RabbitmqClusterDefaultUser {
	if in == nil {
		return nil
	}
	out := new(RabbitmqClusterDefaultUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqClusterSecretReference) DeepCopyInto(out *RabbitmqClusterSecretReference) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitmqClusterSecretReference.
func (in *RabbitmqClusterSecretReference) DeepCopy() *RabbitmqClusterSecretReference {
	if in == nil {
		return nil
	}
	out := new(RabbitmqClusterSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqClusterServiceReference) DeepCopyInto(out *RabbitmqClusterServiceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitmqClusterServiceReference.
func (in *RabbitmqClusterServiceReference) DeepCopy() *RabbitmqClusterServiceReference {
	if in == nil {
		return nil
	}
	out := new(RabbitmqClusterServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportURL) DeepCopyInto(out *TransportURL) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportURL.
func (in *TransportURL) DeepCopy() *TransportURL {
	if in == nil {
		return nil
	}
	out := new(TransportURL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransportURL) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportURLList) DeepCopyInto(out *TransportURLList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TransportURL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportURLList.
func (in *TransportURLList) DeepCopy() *TransportURLList {
	if in == nil {
		return nil
	}
	out := new(TransportURLList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransportURLList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportURLSpec) DeepCopyInto(out *TransportURLSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportURLSpec.
func (in *TransportURLSpec) DeepCopy() *TransportURLSpec {
	if in == nil {
		return nil
	}
	out := new(TransportURLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportURLStatus) DeepCopyInto(out *TransportURLStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportURLStatus.
func (in *TransportURLStatus) DeepCopy() *TransportURLStatus {
	if in == nil {
		return nil
	}
	out := new(TransportURLStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Version) DeepCopyInto(out *Version) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Version.
func (in *Version) DeepCopy() *Version {
	if in == nil {
		return nil
	}
	out := new(Version)
	in.DeepCopyInto(out)
	return out
}
