config:
  CHECK_HEARTBEAT: "false"
  CHECK_KDUMP: "false"
  DELAY: "0"
  DELTA: "30"
  DISABLED: "false"
  EVACUATION_RETRIES: "5"
  EVACUABLE_TAG: "evacuable"
  FENCING_TIMEOUT: "30"
  FORCE_ENABLE: "false"
  FORCE_RESERVED_HOST_EVACUATION: "false"
  HASH_INTERVAL: "60"
  HEARTBEAT_TIMEOUT: "120"
  KDUMP_TIMEOUT: "30"
  LEAVE_DISABLED: "false"
  LOGLEVEL: "info"
  ORCHESTRATED_RESTART: "false"
  POLL: "45"
  RESERVED_HOSTS: "false"
  SKIP_SERVERS_WITH_NAME: ""
  SMART_EVACUATION: "false"
  SSL_VERIFY: "true"
  TAGGED_AGGREGATES: "true"
  TAGGED_FLAVORS: "true"
  TAGGED_IMAGES: "true"
  THRESHOLD: "50"
  WORKERS: "4"
