/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group redis --version v1beta1 --kind Redis --plural redises --programmatic-validation --defaulting
//

package v1beta1

import (
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
        "k8s.io/apimachinery/pkg/runtime/schema"
        "k8s.io/apimachinery/pkg/util/validation/field"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"

	topologyv1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
	common_webhook "github.com/openstack-k8s-operators/lib-common/modules/common/webhook"
)

// RedisDefaults -
type RedisDefaults struct {
	ContainerImageURL string
}

var redisDefaults RedisDefaults

// log is for logging in this package.
var redislog = logf.Log.WithName("redis-resource")

// SetupRedisDefaults - initialize Redis spec defaults for use with either internal or external webhooks
func SetupRedisDefaults(defaults RedisDefaults) {
	redisDefaults = defaults
	redislog.Info("Redis defaults initialized", "defaults", defaults)
}

// SetupWebhookWithManager sets up the webhook with the Manager
func (r *Redis) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-redis-openstack-org-v1beta1-redis,mutating=true,failurePolicy=fail,sideEffects=None,groups=redis.openstack.org,resources=redises,verbs=create;update,versions=v1beta1,name=mredis.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &Redis{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *Redis) Default() {
	redislog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this Redis spec
func (spec *RedisSpec) Default() {
	if spec.ContainerImage == "" {
		spec.ContainerImage = redisDefaults.ContainerImageURL
	}
	spec.RedisSpecCore.Default()
}

// Default - common validations go here (for the OpenStackControlplane which uses this one)
func (spec *RedisSpecCore) Default() {
	//nothing to validate yet
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-redis-openstack-org-v1beta1-redis,mutating=false,failurePolicy=fail,sideEffects=None,groups=redis.openstack.org,resources=redises,verbs=create;update,versions=v1beta1,name=vredis.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &Redis{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *Redis) ValidateCreate() (admission.Warnings, error) {
	redislog.Info("validate create", "name", r.Name)
	var allErrs field.ErrorList
	var allWarn []string
	basePath := field.NewPath("spec")

	allErrs = common_webhook.ValidateDNS1123Label(
		field.NewPath("metadata").Child("name"),
		[]string{r.Name},
		CrMaxLengthCorrection,
	) // omit issue with  statefulset pod label "controller-revision-hash": "<statefulset_name>-<hash>"

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	if r.Spec.TopologyRef != nil {
		if err := topologyv1.ValidateTopologyNamespace(r.Spec.TopologyRef.Namespace, *basePath, r.Namespace); err != nil {
			allErrs = append(allErrs, err)
		}
	}

	if len(allErrs) != 0 {
		return allWarn, apierrors.NewInvalid(
			schema.GroupKind{Group: "redis.openstack.org", Kind: "Redis"},
			r.Name, allErrs,
		)
	}

	return allWarn, nil

}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *Redis) ValidateUpdate(_ runtime.Object) (admission.Warnings, error) {
	redislog.Info("validate update", "name", r.Name)

	var allErrs field.ErrorList
	var allWarn []string
	basePath := field.NewPath("spec")

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	if r.Spec.TopologyRef != nil {
		if err := topologyv1.ValidateTopologyNamespace(r.Spec.TopologyRef.Namespace, *basePath, r.Namespace); err != nil {
			allErrs = append(allErrs, err)
		}
	}
	return allWarn, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *Redis) ValidateDelete() (admission.Warnings, error) {
	redislog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}
