# permissions for end users to view ipsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ipset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: infra-operator
    app.kubernetes.io/part-of: infra-operator
    app.kubernetes.io/managed-by: kustomize
  name: ipset-viewer-role
rules:
- apiGroups:
  - network.openstack.org
  resources:
  - ipsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - ipsets/status
  verbs:
  - get
