apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: infra-operator
    app.kubernetes.io/part-of: infra-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openstackclient
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openstackclient-role
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - patch
  - post
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstackclient-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstackclient-role
subjects:
  # Applying the role to both SA (with and without prefix) to be able
  # to run the operator local
- kind: ServiceAccount
  name: infra-operator-openstackclient
  namespace: openstack
- kind: ServiceAccount
  name: openstackclient
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: memcached-role
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - patch
  - post
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: memcached-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: memcached-role
subjects:
  # Applying the role to the SA (with prefix) to be able
  # to run the operator locally
- kind: ServiceAccount
  name: infra-operator-memcached
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: network-role
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - patch
  - post
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: network-role
subjects:
  # Applying the role to the SA (with prefix) to be able
  # to run the operator locally
- kind: ServiceAccount
  name: infra-operator-network
  namespace: openstack
