/*
Copyright 2023.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group client --version v1beta1 --kind InstanceHa --programmatic-validation --defaulting
//

package v1beta1

import (
	"context"
	"fmt"
	"strings"

	"k8s.io/apimachinery/pkg/runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/validation/field"
)

// InstanceHaDefaults -
type InstanceHaDefaults struct {
	ContainerImageURL string
}

var instanceHaDefaults InstanceHaDefaults

// log is for logging in this package.
var instancehalog = logf.Log.WithName("instanceha-resource")

// SetupInstanceHaDefaults - initialize InstanceHa spec defaults for use with either internal or external webhooks
func SetupInstanceHaDefaults(defaults InstanceHaDefaults) {
	instanceHaDefaults = defaults
	instancehalog.Info("InstanceHa defaults initialized", "defaults", defaults)
}

var _ webhook.Defaulter = &InstanceHa{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *InstanceHa) Default() {
	instancehalog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this InstanceHa spec
func (spec *InstanceHaSpec) Default() {
	if spec.ContainerImage == "" {
		spec.ContainerImage = instanceHaDefaults.ContainerImageURL
	}
	if spec.OpenStackCloud == "" {
		spec.OpenStackCloud = OpenStackCloud
	}
	if spec.OpenStackConfigMap == "" {
		spec.OpenStackConfigMap = "openstack-config"
	}
	if spec.OpenStackConfigSecret == "" {
		spec.OpenStackConfigSecret = "openstack-config-secret"
	}
	if spec.FencingSecret == "" {
		spec.FencingSecret = "fencing-secret"
	}
	if spec.InstanceHaConfigMap == "" {
		spec.InstanceHaConfigMap = "instanceha-config"
	}
	if spec.InstanceHaKdumpPort == 0 {
		spec.InstanceHaKdumpPort = 7410
	}
	if spec.InstanceHaHeartbeatPort == 0 {
		spec.InstanceHaHeartbeatPort = 7411
	}
	if spec.MetricsTLS.MinTLSVersion == "" {
		spec.MetricsTLS.MinTLSVersion = "1.2"
	}
	if spec.MetricsTLS.CipherSuites == "" {
		spec.MetricsTLS.CipherSuites = "HIGH:!aNULL:!MD5:!RC4:!3DES:!kRSA"
	}
}

// ValidateCreate validates the InstanceHa resource on creation.
func (r *InstanceHa) ValidateCreate(ctx context.Context, c client.Client) (admission.Warnings, error) {
	instancehalog.Info("validate create", "name", r.Name)

	var allErrs field.ErrorList
	var allWarn []string
	basePath := field.NewPath("spec")

	allErrs = append(allErrs, r.Spec.ValidateTopology(basePath, r.Namespace)...)
	allErrs = append(allErrs, r.validateUniqueOpenStackCloud(ctx, c, basePath)...)
	allErrs = append(allErrs, r.validateCipherSuites(basePath)...)

	if len(allErrs) != 0 {
		return allWarn, apierrors.NewInvalid(
			schema.GroupKind{Group: "instanceha.openstack.org", Kind: "InstanceHa"},
			r.Name, allErrs)
	}
	return allWarn, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *InstanceHa) ValidateUpdate(ctx context.Context, c client.Client, old runtime.Object) (admission.Warnings, error) {
	instancehalog.Info("validate update", "name", r.Name)

	var allErrs field.ErrorList
	var allWarn []string
	basePath := field.NewPath("spec")

	allErrs = append(allErrs, r.Spec.ValidateTopology(basePath, r.Namespace)...)
	allErrs = append(allErrs, r.validateUniqueOpenStackCloud(ctx, c, basePath)...)
	allErrs = append(allErrs, r.validateCipherSuites(basePath)...)

	if len(allErrs) != 0 {
		return allWarn, apierrors.NewInvalid(
			schema.GroupKind{Group: "instanceha.openstack.org", Kind: "InstanceHa"},
			r.Name, allErrs)
	}
	return allWarn, nil
}

// validateUniqueOpenStackCloud rejects the CR if another InstanceHa in the same
// namespace already targets the same OpenStackCloud value.
func (r *InstanceHa) validateUniqueOpenStackCloud(
	ctx context.Context,
	c client.Client,
	basePath *field.Path,
) field.ErrorList {
	var allErrs field.ErrorList

	instanceHaList := &InstanceHaList{}
	if err := c.List(ctx, instanceHaList, client.InNamespace(r.Namespace)); err != nil {
		allErrs = append(allErrs, field.InternalError(
			basePath.Child("openStackCloud"),
			fmt.Errorf("failed to list InstanceHa resources: %w", err)))
		return allErrs
	}

	for _, existing := range instanceHaList.Items {
		if existing.Name == r.Name {
			continue
		}
		if existing.Spec.OpenStackCloud == r.Spec.OpenStackCloud {
			allErrs = append(allErrs, field.Forbidden(
				basePath.Child("openStackCloud"),
				fmt.Sprintf(
					"InstanceHa %q already manages OpenStackCloud %q in namespace %q",
					existing.Name, r.Spec.OpenStackCloud, r.Namespace)))
			break
		}
	}

	return allErrs
}

// validateCipherSuites rejects cipher strings that would result in unencrypted connections.
func (r *InstanceHa) validateCipherSuites(basePath *field.Path) field.ErrorList {
	var allErrs field.ErrorList
	ciphers := r.Spec.MetricsTLS.CipherSuites
	if ciphers == "" {
		return allErrs
	}
	fldPath := basePath.Child("metricsTLS", "cipherSuites")
	upper := strings.ToUpper(ciphers)
	for _, token := range strings.Split(upper, ":") {
		trimmed := strings.TrimLeft(token, "+")
		switch trimmed {
		case "NULL", "ENULL", "ANULL":
			allErrs = append(allErrs, field.Invalid(fldPath, ciphers,
				fmt.Sprintf("cipher string must not include %q without a '!' prefix", token)))
		case "ALL":
			allErrs = append(allErrs, field.Invalid(fldPath, ciphers,
				"cipher string must not use 'ALL' (includes NULL ciphers); use 'HIGH' instead"))
		}
		if strings.HasPrefix(trimmed, "@SECLEVEL=0") {
			allErrs = append(allErrs, field.Invalid(fldPath, ciphers,
				"cipher string must not use '@SECLEVEL=0' (disables all security requirements)"))
		}
	}
	return allErrs
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *InstanceHa) ValidateDelete() (admission.Warnings, error) {
	instancehalog.Info("validate delete", "name", r.Name)

	return nil, nil
}
