apiVersion: instanceha.openstack.org/v1beta1
kind: InstanceHa
metadata:
  name: instanceha
spec:
  caBundleSecretName: combined-ca-bundle
  #disabled: "False"
  #containerImage: "quay.io/openstack-s2i-containers/openstack-openstackclient:master-latest"
  #networkAttachments: ['internalapi']
  #openStackCloud: "default"
  #openStackConfigMap:
  #openStackConfigSecret:
  #fencingSecret:
  #instanceHaConfigMap:
  #instanceHaKdumpPort:
  #instanceHaHeartbeatPort:
